name: Publish Docker Image

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_target: [ 'amd64:linux/amd64', 'arm64:linux/arm64']
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker buildx ${{ matrix.docker_target }}
        run: |
          DOCKER_FILE=Dockerfile.$(echo "${{ matrix.docker_target }}" | cut -f1 -d:)
          DOCKER_IMAGE=windoze/feathrpiper:latest
          DOCKER_PLATFORM=$(echo "${{ matrix.docker_target }}" | cut -f2 -d:)
          docker buildx build . --no-cache --platform ${DOCKER_PLATFORM} -t "${DOCKER_IMAGE}" -f "${DOCKER_FILE}" --push
